"""
src/features/bio_scoring.py
Biological substitution matrices (BLOSUM62, PAM250) and Grantham scores.
Used for quantifying the biochemical severity of amino acid substitutions.
"""

from __future__ import annotations

from typing import Dict, Tuple

# BLOSUM62 Substitution Matrix
# Keys are (AA1, AA2), value is the score.
BLOSUM62: Dict[Tuple[str, str], int] = {
    ("A", "A"): 4,
    ("A", "R"): -1,
    ("A", "N"): -2,
    ("A", "D"): -2,
    ("A", "C"): 0,
    ("A", "Q"): -1,
    ("A", "E"): -1,
    ("A", "G"): 0,
    ("A", "H"): -2,
    ("A", "I"): -1,
    ("A", "L"): -1,
    ("A", "K"): -1,
    ("A", "M"): -1,
    ("A", "F"): -2,
    ("A", "P"): -1,
    ("A", "S"): 1,
    ("A", "T"): 0,
    ("A", "W"): -3,
    ("A", "Y"): -2,
    ("A", "V"): 0,
    ("R", "R"): 5,
    ("R", "N"): 0,
    ("R", "D"): -2,
    ("R", "C"): -3,
    ("R", "Q"): 1,
    ("R", "E"): 0,
    ("R", "G"): -2,
    ("R", "H"): 0,
    ("R", "I"): -3,
    ("R", "L"): -2,
    ("R", "K"): 2,
    ("R", "M"): -1,
    ("R", "F"): -3,
    ("R", "P"): -2,
    ("R", "S"): -1,
    ("R", "T"): -1,
    ("R", "W"): -3,
    ("R", "Y"): -2,
    ("R", "V"): -3,
    ("N", "N"): 6,
    ("N", "D"): 1,
    ("N", "C"): -3,
    ("N", "Q"): 0,
    ("N", "E"): 0,
    ("N", "G"): 0,
    ("N", "H"): 1,
    ("N", "I"): -3,
    ("N", "L"): -3,
    ("N", "K"): 0,
    ("N", "M"): -2,
    ("N", "F"): -3,
    ("N", "P"): -2,
    ("N", "S"): 1,
    ("N", "T"): 0,
    ("N", "W"): -4,
    ("N", "Y"): -2,
    ("N", "V"): -3,
    ("D", "D"): 6,
    ("D", "C"): -3,
    ("D", "Q"): 0,
    ("D", "E"): 2,
    ("D", "G"): -1,
    ("D", "H"): -1,
    ("D", "I"): -3,
    ("D", "L"): -4,
    ("D", "K"): -1,
    ("D", "M"): -3,
    ("D", "F"): -3,
    ("D", "P"): -1,
    ("D", "S"): 0,
    ("D", "T"): -1,
    ("D", "W"): -4,
    ("D", "Y"): -3,
    ("D", "V"): -3,
    ("C", "C"): 9,
    ("C", "Q"): -3,
    ("C", "E"): -4,
    ("C", "G"): -3,
    ("C", "H"): -3,
    ("C", "I"): -1,
    ("C", "L"): -1,
    ("C", "K"): -3,
    ("C", "M"): -1,
    ("C", "F"): -2,
    ("C", "P"): -3,
    ("C", "S"): -1,
    ("C", "T"): -1,
    ("C", "W"): -2,
    ("C", "Y"): -2,
    ("C", "V"): -1,
    ("Q", "Q"): 5,
    ("Q", "E"): 2,
    ("Q", "G"): -2,
    ("Q", "H"): 0,
    ("Q", "I"): -3,
    ("Q", "L"): -2,
    ("Q", "K"): 1,
    ("Q", "M"): 0,
    ("Q", "F"): -3,
    ("Q", "P"): -1,
    ("Q", "S"): 0,
    ("Q", "T"): -1,
    ("Q", "W"): -2,
    ("Q", "Y"): -1,
    ("Q", "V"): -2,
    ("E", "E"): 5,
    ("E", "G"): -2,
    ("E", "H"): 0,
    ("E", "I"): -3,
    ("E", "L"): -3,
    ("E", "K"): 1,
    ("E", "M"): -2,
    ("E", "F"): -3,
    ("E", "P"): -1,
    ("E", "S"): 0,
    ("E", "T"): -1,
    ("E", "W"): -3,
    ("E", "Y"): -2,
    ("E", "V"): -2,
    ("G", "G"): 6,
    ("G", "H"): -2,
    ("G", "I"): -4,
    ("G", "L"): -4,
    ("G", "K"): -2,
    ("G", "M"): -3,
    ("G", "F"): -3,
    ("G", "P"): -2,
    ("G", "S"): 0,
    ("G", "T"): -2,
    ("G", "W"): -2,
    ("G", "Y"): -3,
    ("G", "V"): -3,
    ("H", "H"): 8,
    ("H", "I"): -3,
    ("H", "L"): -3,
    ("H", "K"): -1,
    ("H", "M"): -2,
    ("H", "F"): -1,
    ("H", "P"): -2,
    ("H", "S"): -1,
    ("H", "T"): -2,
    ("H", "W"): -2,
    ("H", "Y"): 2,
    ("H", "V"): -3,
    ("I", "I"): 4,
    ("I", "L"): 2,
    ("I", "K"): -3,
    ("I", "M"): 1,
    ("I", "F"): 0,
    ("I", "P"): -3,
    ("I", "S"): -2,
    ("I", "T"): -1,
    ("I", "W"): -3,
    ("I", "Y"): -1,
    ("I", "V"): 3,
    ("L", "L"): 4,
    ("L", "K"): -2,
    ("L", "M"): 2,
    ("L", "F"): 0,
    ("L", "P"): -3,
    ("L", "S"): -2,
    ("L", "T"): -1,
    ("L", "W"): -2,
    ("L", "Y"): -1,
    ("L", "V"): 1,
    ("K", "K"): 5,
    ("K", "M"): -1,
    ("K", "F"): -3,
    ("K", "P"): -1,
    ("K", "S"): 0,
    ("K", "T"): -1,
    ("K", "W"): -3,
    ("K", "Y"): -2,
    ("K", "V"): -2,
    ("M", "M"): 5,
    ("M", "F"): 0,
    ("M", "P"): -2,
    ("M", "S"): -1,
    ("M", "T"): -1,
    ("M", "W"): -1,
    ("M", "Y"): -1,
    ("M", "V"): 1,
    ("F", "F"): 6,
    ("F", "P"): -4,
    ("F", "S"): -2,
    ("F", "T"): -2,
    ("F", "W"): 1,
    ("F", "Y"): 3,
    ("F", "V"): -1,
    ("P", "P"): 7,
    ("P", "S"): -1,
    ("P", "T"): -1,
    ("P", "W"): -4,
    ("P", "Y"): -3,
    ("P", "V"): -2,
    ("S", "S"): 4,
    ("S", "T"): 1,
    ("S", "W"): -3,
    ("S", "Y"): -2,
    ("S", "V"): -2,
    ("T", "T"): 5,
    ("T", "W"): -2,
    ("T", "Y"): -2,
    ("T", "V"): 0,
    ("W", "W"): 11,
    ("W", "Y"): 2,
    ("W", "V"): -3,
    ("Y", "Y"): 7,
    ("Y", "V"): -1,
    ("V", "V"): 4,
}

# Complete the symmetric part of BLOSUM62
all_aas = "ARNDCQEGHILKMFPSTWYV"
for aa1 in all_aas:
    for aa2 in all_aas:
        if (aa1, aa2) not in BLOSUM62 and (aa2, aa1) in BLOSUM62:
            BLOSUM62[(aa1, aa2)] = BLOSUM62[(aa2, aa1)]


def get_blosum62_score(ref: str, alt: str) -> int:
    """Returns the substitution score for ref -> alt. Lower (more negative) is more severe."""
    return BLOSUM62.get((ref.upper(), alt.upper()), -4)


# Grantham Score (Chemical difference)
# Higher is more severe/different.
GRANTHAM_PROPS = {
    "A": (8.1, 31, 1.15),
    "R": (10.5, 124, 1.81),
    "N": (11.6, 56, 1.50),
    "D": (13.0, 54, 1.50),
    "C": (5.5, 55, 1.34),
    "Q": (10.5, 85, 1.56),
    "E": (12.3, 83, 1.56),
    "G": (9.0, 3, 0.00),
    "H": (10.4, 81, 2.99),
    "I": (5.2, 111, 4.41),
    "L": (4.9, 111, 4.41),
    "K": (11.3, 119, 1.89),
    "M": (5.7, 105, 3.23),
    "F": (5.2, 132, 5.48),
    "P": (8.0, 42, 2.35),
    "S": (9.2, 32, 1.43),
    "T": (8.6, 61, 1.43),
    "W": (5.4, 170, 7.63),
    "Y": (6.2, 136, 5.89),
    "V": (5.9, 84, 3.12),
}

GRANTHAM_PROPERTIES = GRANTHAM_PROPS  # Canonical alias


def get_grantham_score(ref: str, alt: str) -> float:
    """Calculates Grantham score between two amino acids."""
    r, a = ref.upper(), alt.upper()
    if r not in GRANTHAM_PROPERTIES or a not in GRANTHAM_PROPERTIES:
        return 100.0  # Default fallback

    p1 = GRANTHAM_PROPERTIES[r]
    p2 = GRANTHAM_PROPERTIES[a]

    # Weights from Grantham (1974)
    alpha, beta, gamma = 1.833, 0.1018, 0.00039

    d = (alpha * (p1[0] - p2[0]) ** 2 + beta * (p1[1] - p2[1]) ** 2 + gamma * (p1[2] - p2[2]) ** 2) ** 0.5
    return float(d)
